spring:
  jpa:
    hibernate:
      ddl-auto: create # 자동으로 테이블을 만들어줌
    properties:
      hibernate :
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100  # 인쿼리의 개수에 따라 루프를 돈다.  100일 때 튜플이 1000개라면 10번 루프를 돌음.

  datasource:
    sql-script-encoding: utf-8
    driverClassName: org.postgresql.Driver #데이터 소스 설정
    url: jdbc:postgresql://localhost:5432/test
    username: mac
    password: root

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging.level:
  org.hibernate.SQL: debug # JPA 가 실행하는 SQL이 모두 보이게 함
#  org.hibernate.type: trace   #

server:
  port=8080:

